# Generated by Django 5.2.7 on 2025-11-01 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50)),
                ('descricao_categoria', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prato', models.CharField(max_length=50)),
                ('descricao_prato', models.TextField(blank=True)),
                ('preco_prato', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagem_prato', models.IntegerField(blank=True, null=True)),
                ('disponibilidade', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratos', to='sitebar.categoria_prato')),
            ],
        ),
    ]
