# Generated by Django 5.2.7 on 2025-11-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='ingredientes_prato',
            field=models.TextField(blank=True),
        ),
    ]
