# Generated by Django 5.2.7 on 2025-11-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebar', '0002_prato_ingredientes_prato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prato',
            name='disponibilidade',
        ),
        migrations.AddField(
            model_name='prato',
            name='tipico',
            field=models.BooleanField(default=False),
        ),
    ]
