# Generated by Django 5.2.7 on 2025-11-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebar', '0003_remove_prato_disponibilidade_prato_tipico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='imagem_prato',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
