# Generated by Django 5.2.7 on 2025-11-03 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitebar", "0004_alter_prato_imagem_prato"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
                (
                    "jogadores",
                    models.CharField(help_text="Ex: 2-6 jogadores", max_length=20),
                ),
                ("tempo_partida", models.CharField(max_length=50)),
                ("descricao_curta", models.CharField(max_length=200)),
                ("descricao_detalhada", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="jogos/"),
                ),
                ("total_copias", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="RegistroUsoJogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "jogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="sitebar.jogo",
                    ),
                ),
            ],
        ),
    ]
